import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { getMovies } from '@/lib/utils';
import { count } from 'console';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const movies = await getMovies();

  const allGenres = movies.flatMap((movie) =>
    movie.Genre.replaceAll(' ', '').split(',')
  );

  const allCountries = movies.flatMap((movie) =>
    movie.Country.split(',').map((country) => country.trim().replace(/ /g, '-'))
  );
  // membuat array baru dari genreuniq
  const genres = [...new Set(allGenres)];
  const countries = [...new Set(allCountries)];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <Header genres={genres} countries={countries} />
        <div className="flex-1">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
